<<<<<<< HEAD
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
=======
import './globals.css';

export const metadata = {
  title: 'Tasks App',
  description: 'Task management for hotel operations',
>>>>>>> 23560ab6353411598ab1a5fbda00da7b42be86dc
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
<<<<<<< HEAD
      <body>{children}</body>
    </html>
  )
}
=======
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
      </head>
      <body>{children}</body>
    </html>
  )
}
>>>>>>> 23560ab6353411598ab1a5fbda00da7b42be86dc
